---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: demo-gauge
  name: demo-gauge
  namespace: demo-gauge
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hono-example-demo-gauge
