---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  port:
    targetPort: 3000-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: grafana
